### ISSUE TITLE
1. Introducing Variables

### ISSUE THREAD

**Issue by joedmcrae** [MakeSchool-Tutorials/Intro-Variables-Swift#2]
In the last clock exercise, the secondsrotation variable is set to 0 at the end of the playground, so any edits to secondsrotations during the first task will not be reflected in the visualization.  

Also - my playground needed all of the rotation variables to explicitly be set to the Double variable type to run.

**Comment by dionlarson** [comment]
Fixed in 48fec80 and 43d52bb. Thank you!
